import ReferralCard from "./components/ReferralCard";
import ReferralTable from "./components/ReferralTable";
import { IoMdMail } from "react-icons/io";
import { IoMailOpen } from "react-icons/io5";
import { IoMailUnread } from "react-icons/io5";
import { useTranslation } from "react-i18next";

interface ReferralProps {}

const fakeData = [
    {
        title: "Referrals",
        total: 125,
        type: "number",
        content:
            "The number of visits generated by promotions. Measures the reach and effectiveness of promotional campaigns in driving traffic",
        icon: <IoMdMail size={30} />,
        className: "bg-dashboard-blue/30 text-dashboard-blue",
    },
    {
        title: "Referrals Converted",
        total: (125 / 678) * 100,
        type: "percent",
        content:
            "The percentage of promotional traffic that results in a sale or desired action. Indicates the efficiency of campaigns in turning interest into revenue",

        icon: <IoMailOpen size={30} />,
        className: "bg-dashboard-violet/30 text-dashboard-violet",
    },
    {
        title: "Referrals Pending",
        total: 678,
        type: "number",
        content:
            "The total number of promotions executed. Helps assess the scale of promotional efforts and their overall contribution to business growth",

        icon: <IoMailUnread size={30} />,
        className: "bg-dashboard-green/30 text-dashboard-green",
    },
];

const Referral: React.FC<ReferralProps> = () => {
    const { t } = useTranslation();
    return (
        <div className="w-full h-auto flex flex-col gap-3">
            <div className="h-auto w-full flex flex-col justify-start items-start gap-3 bg-white p-5 rounded-md">
                <span className=" text-lg font-bold text-primary">
                    {t("Your Referral Stats")}
                </span>

                <div className="w-full h-full flex justify-between items-center gap-3 pb-5 bg-white ">
                    {fakeData.map((item, index) => (
                        <ReferralCard
                            key={index}
                            title={t(item.title)}
                            total={item.total}
                            icon={item.icon}
                            type={item.type}
                            content={t(item.content)}
                            className={item.className}
                        />
                    ))}
                </div>
            </div>
            <ReferralTable />
        </div>
    );
};
export default Referral;
